spring.application.name=crudmovimiento_Julio
server.port=8081
server.servlet.context-path=/snpp2
spring.datasource.url=jdbc:mysql://localhost:3306/bd_mov_julio?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true